### ISSUE TITLE
Wiki i wycieczka

### ISSUE THREAD

**Issue by clutroth** [maciejfic/SOK#10]
Może zrobilibyśmy słownik w wiki? Może być to przydatne przy dyskusjach.
Na przykład, ja mam propozycję, żeby to już członek rodziny miał możliwość zgłoszenia propozycji wycieczki, niech mają coś z życia :D

**Comment by maciejfic** [comment]
Pomysł brzmi spoko, ale to nie od nas zależy. Zamawiający musi ustalić takie rzeczy.

**Comment by bladekp** [comment]
ja w swoich dokumentach zakładam że członek rodziny może dodać wycieczkę
