### ISSUE TITLE
Wymagania klienta

### ISSUE THREAD

**Issue by maciejfic** [maciejfic/SOK#8]
Zadanie polega na stworzeniu dokumentu, który zawiera opis wszystkich przekazanych przez zamawiającego wymagań, opis kim jest zamawiający oraz opis żądań klienta. Plik podobny do załączonego:
https://cdn.fbsbx.com/hphotos-xfa1/v/t59.2708-21/10962471_10202632937383463_2060094757_n.pdf/PIO_1.pdf?oh=1186668498f495a8936b421fdb0aacb2&oe=550DF045&dl=1

**Comment by bedzkowp** [comment]
Co konkretnie ma się znaleźć w tym dokumencie i jaki jest jego cel?

**Comment by clutroth** [comment]
przejmuję ten burdel.
