### ISSUE TITLE
Przypadki użycia - literówka

### ISSUE THREAD

**Issue by clutroth** [maciejfic/SOK#9]
Projekt Zespołowy
wykonany pod kierownictwem
dr inż. Ryszard Łagoda

Czy nie powinno być może "Ryszarda Łagody"? Zgłaszam, nie poprawiam, bo nie chcę się wpieprzać w cudzy kod, jak chcesz, to poprawię.
Mamy więcej Iśusów - więcej pracujemy :smile:

**Comment by bladekp** [comment]
ok
